'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class eSaludEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=eSaludEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property citas() As DbSet(Of cita)
    Public Property cuadrantes() As DbSet(Of cuadrante)
    Public Property especialidades() As DbSet(Of especialidad)
    Public Property horas() As DbSet(Of hora)
    Public Property medicos() As DbSet(Of medico)
    Public Property pacientes() As DbSet(Of paciente)

End Class
