'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cita
    Public Property id As Integer
    Public Property paciente As String
    Public Property cuadrante As Integer

    Public Overridable Property CitaSuCuadrante As cuadrante
    Public Overridable Property CitaSuPaciente As paciente

End Class
