'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cuadrante
    Public Property id As Integer
    Public Property dia As Date
    Public Property hora As String
    Public Property medico As String
    Public Property disponible As Boolean

    Public Overridable Property cuadranteCita As ICollection(Of cita) = New HashSet(Of cita)
    Public Overridable Property cuadranteHora As hora
    Public Overridable Property cuadranteMedico As medico

End Class
