'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class medico
    Public Property nif As String
    Public Property colegiado As String
    Public Property nombre As String
    Public Property telefono As String
    Public Property email As String
    Public Property password As String
    Public Property rama As Integer

    Public Overridable Property cuadranteDelMedico As ICollection(Of cuadrante) = New HashSet(Of cuadrante)
    Public Overridable Property especialidadDelMedico As especialidad

End Class
